#!/usr/bin/env python
"""
Synthetic POMDP MST environment + agent loop.

This module assumes dataset entries generated by notebooks/generate_pomdp_mst_synthetic.py.
"""

from __future__ import annotations

import json
import random
import re
from dataclasses import dataclass, field
from typing import Callable


Action = tuple[str, int]


@dataclass
class AgentState:
    observation: dict
    task_id: str | None = None
    history: list[dict] = field(default_factory=list)
    selected_edges: list[int] = field(default_factory=list)
    known_endpoints: dict[int, tuple[int, int]] = field(default_factory=dict)
    steps: int = 0


class POMDPMSTAgent:
    def __init__(
        self,
        llm: Callable[[str], str] | None = None,
        seed: int = 7,
        trace: list[dict] | None = None,
        print_io: bool = False,
    ) -> None:
        self.llm = llm
        self.rng = random.Random(seed)
        self.trace = trace
        self.print_io = print_io

    def action(self, state: AgentState) -> Action:
        prompt = self._build_prompt(state)
        llm_output = self.llm(prompt) if self.llm is not None else ""
        parsed = self._parse_action(llm_output)
        chosen = parsed if parsed is not None else self._fallback_action(state)
        if self.trace is not None:
            self.trace.append(
                {
                    "task_id": state.task_id,
                    "step": state.steps,
                    "prompt": prompt,
                    "llm_output": llm_output,
                    "parsed_action": parsed,
                    "chosen_action": chosen,
                }
            )
        if self.print_io:
            print(f"\n=== task {state.task_id} step {state.steps} ===")
            print("PROMPT:")
            print(prompt)
            print("OUTPUT:")
            print(llm_output)
            print(f"PARSED: {parsed}")
            print(f"CHOSEN: {chosen}")
        if parsed is not None:
            return parsed
        return chosen

    def _build_prompt(self, state: AgentState) -> str:
        obs = state.observation
        payload = {
            "num_nodes": obs["num_nodes"],
            "num_edges": obs["num_edges"],
            "edge_weights": obs["edge_weights"],
            "selected_edges": state.selected_edges,
            "known_endpoints": {str(k): list(v) for k, v in state.known_endpoints.items()},
            "history_tail": state.history[-5:],
            "instruction": "Return one action: query_edge(<idx>) or select_edge(<idx>).",
        }
        return json.dumps(payload, ensure_ascii=True)

    def _parse_action(self, text: str) -> Action | None:
        if not text:
            return None
        match = re.search(r"(query_edge|select_edge)\s*\(\s*(\d+)\s*\)", text)
        if not match:
            return None
        action_type = match.group(1)
        edge_idx = int(match.group(2))
        return action_type, edge_idx

    def _fallback_action(self, state: AgentState) -> Action:
        num_edges = state.observation["num_edges"]
        unknown_edges = [i for i in range(num_edges) if i not in state.known_endpoints]
        if unknown_edges:
            return "query_edge", self.rng.choice(unknown_edges)
        return "select_edge", self.rng.randrange(num_edges)


class POMDPMSTEnvironment:
    def __init__(self, entry: dict) -> None:
        self.entry = entry
        self.num_nodes = entry["observation"]["num_nodes"]
        self.num_edges = entry["observation"]["num_edges"]
        self.edge_endpoints = [tuple(x) for x in entry["hidden_graph"]["edge_endpoints"]]
        self.edge_weights = entry["observation"]["edge_weights"]
        self.mst_weight = entry["oracle"]["mst_weight"]

    def initial_state(self) -> AgentState:
        return AgentState(task_id=self.entry.get("task_id"), observation=self.entry["observation"])

    def state(self, state: AgentState) -> dict:
        return {
            "observation": state.observation,
            "history": state.history,
            "selected_edges": state.selected_edges,
            "known_endpoints": {str(k): list(v) for k, v in state.known_endpoints.items()},
            "steps": state.steps,
        }

    def transition(self, state: AgentState, action: Action) -> tuple[AgentState, dict]:
        action_type, edge_idx = action
        state.steps += 1

        if edge_idx < 0 or edge_idx >= self.num_edges:
            info = {"ok": False, "reason": "edge_index_out_of_range"}
            state.history.append({"action": action, "result": info})
            return state, info

        if action_type == "query_edge":
            endpoints = self.edge_endpoints[edge_idx]
            state.known_endpoints[edge_idx] = endpoints
            info = {"ok": True, "endpoints": endpoints}
            state.history.append({"action": action, "result": info})
            return state, info

        if action_type == "select_edge":
            success, reason = self._try_add_edge(state, edge_idx)
            info = {"ok": success, "reason": reason}
            state.history.append({"action": action, "result": info})
            return state, info

        info = {"ok": False, "reason": "unknown_action"}
        state.history.append({"action": action, "result": info})
        return state, info

    def reward(self, state: AgentState, done: bool) -> float:
        if not done:
            return 0.0
        if len(state.selected_edges) != self.num_nodes - 1:
            return 0.0
        tree_weight = sum(self.edge_weights[i] for i in state.selected_edges)
        if tree_weight <= 0:
            return 0.0
        return float(self.mst_weight) / float(tree_weight)

    def is_done(self, state: AgentState, max_steps: int) -> bool:
        return len(state.selected_edges) == self.num_nodes - 1 or state.steps >= max_steps

    def _try_add_edge(self, state: AgentState, edge_idx: int) -> tuple[bool, str]:
        if edge_idx in state.selected_edges:
            return False, "already_selected"
        endpoints = self.edge_endpoints[edge_idx]
        if self._creates_cycle(state.selected_edges, endpoints):
            return False, "cycle"
        state.selected_edges.append(edge_idx)
        return True, "added"

    def _creates_cycle(self, selected_edges: list[int], new_edge: tuple[int, int]) -> bool:
        parent = list(range(self.num_nodes))

        def find(x: int) -> int:
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x

        def union(a: int, b: int) -> bool:
            ra, rb = find(a), find(b)
            if ra == rb:
                return False
            parent[rb] = ra
            return True

        for edge_idx in selected_edges:
            u, v = self.edge_endpoints[edge_idx]
            union(u, v)

        u, v = new_edge
        return not union(u, v)


def run_episode(entry: dict, agent: POMDPMSTAgent, max_steps: int = 30) -> dict:
    env = POMDPMSTEnvironment(entry)
    state = env.initial_state()

    while True:
        action = agent.action(state)
        state, _ = env.transition(state, action)
        done = env.is_done(state, max_steps)
        if done:
            reward = env.reward(state, done=True)
            return {
                "task_id": entry["task_id"],
                "selected_edges": state.selected_edges,
                "steps": state.steps,
                "reward": reward,
                "done": True,
            }
