"""
Plot figures from statistics generated by verify_kv_error.py.

Usage:
  python verify_kv_plot.py \
    --results_path ./prop31_results/verify_kv_results.pt \
    --save_dir ./prop31_figures
"""

import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import rc
from matplotlib.ticker import LogLocator, NullFormatter, FuncFormatter
import numpy as np
import torch


# =====================================================================
# Global style (matches the reference plot)
# =====================================================================

rc('font', **{'family': 'sans-serif', 'sans-serif': ['Helvetica']})
mpl.rcParams['savefig.dpi'] = 1200
mpl.rcParams['text.usetex'] = True


# =====================================================================
# Plot helpers
# =====================================================================

GROUP_COLORS = ['royalblue', 'darkorange', 'forestgreen', 'red',
                'mediumpurple', 'saddlebrown', 'deeppink', 'gray']
GROUP_MARKERS = ['o', 's', 'D', '^', 'v', 'P', 'X', 'h']


def piecewise_compress_x(x_vals, compress_until=50, left_ratio=1.0 / 3.0):
    x_vals = np.asarray(x_vals, dtype=float)
    x_min, x_max = float(np.min(x_vals)), float(np.max(x_vals))
    if x_max <= x_min or compress_until <= x_min or compress_until >= x_max:
        return x_vals.copy()
    ratio = float(np.clip(left_ratio, 0.05, 0.95))
    out = np.empty_like(x_vals, dtype=float)
    left = x_vals <= compress_until
    out[left] = ((x_vals[left] - x_min) / (compress_until - x_min)) * ratio
    out[~left] = ratio + ((x_vals[~left] - compress_until) / (x_max - compress_until)) * (1.0 - ratio)
    out = x_min + out * (x_max - x_min)
    return out


def choose_xticks_with_labels(x_min, x_max):
    cands = [1, 2, 5, 10, 20, 30, 40, 50, 75, 100, 150, 200, 300, 500, 800, 1000, 1500, 2000]
    raw = [x for x in cands if x_min <= x <= x_max]
    if not raw:
        raw = np.linspace(x_min, x_max, 6).astype(int).tolist()
    if x_min not in raw:
        raw.insert(0, int(x_min))
    if x_max not in raw:
        raw.append(int(x_max))
    raw = sorted(set(raw))
    return np.array(raw, dtype=float), [rf'$\mathrm{{{int(x)}}}$' for x in raw]


def prune_tick_labels(raw_ticks, scaled_ticks, min_gap_ratio=0.07):
    raw_ticks = np.asarray(raw_ticks, dtype=float)
    scaled_ticks = np.asarray(scaled_ticks, dtype=float)
    if len(raw_ticks) <= 2:
        return raw_ticks
    span = float(np.max(scaled_ticks) - np.min(scaled_ticks))
    if span <= 0:
        return raw_ticks
    min_gap = min_gap_ratio * span
    keep_idx = [0]
    last_idx = 0
    for i in range(1, len(raw_ticks) - 1):
        if (scaled_ticks[i] - scaled_ticks[last_idx]) >= min_gap:
            keep_idx.append(i)
            last_idx = i
    keep_idx.append(len(raw_ticks) - 1)
    keep_idx = sorted(set(keep_idx))
    return raw_ticks[keep_idx]


def latex_sci_formatter(val, pos):
    """Format y-axis tick in LaTeX scientific notation."""
    if val == 0:
        return r'$\mathrm{0}$'
    exp = int(np.floor(np.log10(abs(val))))
    coeff = val / 10 ** exp
    if abs(coeff - 1.0) < 0.01:
        return rf'$10^{{{exp}}}$'
    return rf'${coeff:.1f} \times 10^{{{exp}}}$'


# =====================================================================
# Check 1 plots
# =====================================================================

def plot_term1(term1_results, save_dir, x_compress_until=50, x_left_ratio=1.0 / 3.0):
    for item in term1_results:
        prefix_len = item["prefix_length"]
        groups = item["groups"]
        suffix = f"L{prefix_len}"

        # ── Singular value decay ──
        fig, ax = plt.subplots(1, 1, figsize=(7, 6))
        x_max = 1
        for g_item in groups:
            gid = g_item["group"]
            s_sq = np.asarray(g_item["singular_values_sq"], dtype=float)
            x_raw = np.arange(1, len(s_sq) + 1, dtype=float)
            x_sc = piecewise_compress_x(x_raw, x_compress_until, x_left_ratio)
            ax.semilogy(x_sc, s_sq,
                        marker=GROUP_MARKERS[gid % len(GROUP_MARKERS)],
                        color=GROUP_COLORS[gid % len(GROUP_COLORS)],
                        label=rf'$\mathrm{{Group~{gid}}}$',
                        lw=3, markersize=8,
                        markevery=max(1, len(s_sq) // 15))
            x_max = max(x_max, len(s_sq))

        tr, _ = choose_xticks_with_labels(1, x_max)
        tr_sc = piecewise_compress_x(tr, x_compress_until, x_left_ratio)
        tr_keep = prune_tick_labels(tr, tr_sc, min_gap_ratio=0.08)
        tr_keep_sc = piecewise_compress_x(tr_keep, x_compress_until, x_left_ratio)
        ax.set_xticks(tr_keep_sc)
        ax.set_xticklabels([rf'$\mathrm{{{int(x)}}}$' for x in tr_keep], fontsize=25)
        ax.tick_params(axis='y', labelsize=25)
        ax.set_xlabel(r'$\mathrm{Singular~value~index}~j$', fontsize=28)
        ax.set_ylabel(r'$\sigma_j^2(K^{(g)})$', fontsize=28)
        ax.legend(fontsize=20, loc='upper right')
        ax.grid(True, linestyle='--', linewidth=0.5)
        fig.tight_layout()
        fig.savefig(os.path.join(save_dir, f"term1_sv_decay_{suffix}.pdf"))
        plt.close(fig)

        # ── Tail energy ──
        fig2, ax2 = plt.subplots(1, 1, figsize=(7, 6))
        n_max = 1
        for g_item in groups:
            gid = g_item["group"]
            e_n = np.asarray(g_item["tail_energy"], dtype=float)
            n_vals = np.arange(1, len(e_n) + 1, dtype=float)
            n_max = max(n_max, len(e_n))
            n_sc = piecewise_compress_x(n_vals, x_compress_until, x_left_ratio)
            ax2.semilogy(n_sc, e_n,
                         marker=GROUP_MARKERS[gid % len(GROUP_MARKERS)],
                         color=GROUP_COLORS[gid % len(GROUP_COLORS)],
                         label=rf'$\mathrm{{Group~{gid}}}$',
                         lw=3, markersize=8,
                         markevery=max(1, len(e_n) // 15))

        tr2, _ = choose_xticks_with_labels(1, n_max)
        tr2_sc = piecewise_compress_x(tr2, x_compress_until, x_left_ratio)
        tr2_keep = prune_tick_labels(tr2, tr2_sc, min_gap_ratio=0.08)
        tr2_keep_sc = piecewise_compress_x(tr2_keep, x_compress_until, x_left_ratio)
        ax2.set_xticks(tr2_keep_sc)
        ax2.set_xticklabels([rf'$\mathrm{{{int(x)}}}$' for x in tr2_keep], fontsize=25)
        ax2.tick_params(axis='y', labelsize=25)
        ax2.set_xlabel(r'$\mathrm{HiPPO~state~dimension}~N$', fontsize=28)
        ax2.set_ylabel(r'$E_N^{(g)} = \sum_{j>N} \sigma_j^2$', fontsize=28)
        ax2.legend(fontsize=20, loc='upper right')
        ax2.grid(True, linestyle='--', linewidth=0.5)
        fig2.tight_layout()
        fig2.savefig(os.path.join(save_dir, f"term1_tail_energy_{suffix}.pdf"))
        plt.close(fig2)
        print(f"Saved Check 1 figures for L={prefix_len}.")


# =====================================================================
# Check 2 plots
# =====================================================================

def plot_term2(term2_results, save_dir):
    # ── Max residual ──
    fig_max, ax_max = plt.subplots(1, 1, figsize=(7, 6))
    # ── Weighted residual ──
    fig_wt, ax_wt = plt.subplots(1, 1, figsize=(7, 6))

    for g_item in term2_results["groups"]:
        gid = g_item["group"]
        n_arr = np.asarray(g_item["n_values"], dtype=float)
        max_arr = np.asarray(g_item["max_residual"], dtype=float)
        wt_arr = np.asarray(g_item["weighted_residual"], dtype=float)

        ax_max.loglog(n_arr, max_arr,
                      marker=GROUP_MARKERS[gid % len(GROUP_MARKERS)],
                      color=GROUP_COLORS[gid % len(GROUP_COLORS)],
                      label=rf'$\mathrm{{Group~{gid}}}$',
                      lw=3, markersize=8,
                      markevery=max(1, len(n_arr) // 15))
        ax_wt.loglog(n_arr, wt_arr,
                     marker=GROUP_MARKERS[gid % len(GROUP_MARKERS)],
                     color=GROUP_COLORS[gid % len(GROUP_COLORS)],
                     label=rf'$\mathrm{{Group~{gid}}}$',
                     lw=3, markersize=8,
                     markevery=max(1, len(n_arr) // 15))

    # Format max residual
    ax_max.tick_params(axis='both', labelsize=25)
    ax_max.set_xlabel(r'$\mathrm{HiPPO~state~dimension}~N$', fontsize=28)
    ax_max.set_ylabel(r'$\max_{i \leq K}\, \|(I-P_N)\,u_i^{(g)}\|^2$', fontsize=28)
    ax_max.legend(fontsize=20, loc='upper right')
    ax_max.grid(True, linestyle='--', linewidth=0.5, which='both')
    fig_max.tight_layout()
    path_max = os.path.join(save_dir, "term2_hippo_residual_max.pdf")
    fig_max.savefig(path_max)
    plt.close(fig_max)
    print(f"Saved: {path_max}")

    # Format weighted residual
    ax_wt.tick_params(axis='both', labelsize=25)
    ax_wt.set_xlabel(r'$\mathrm{HiPPO~state~dimension}~N$', fontsize=28)
    ax_wt.set_ylabel(r'$\sum_{i=1}^{K}\sigma_i^2\|(I-P_N)\,u_i^{(g)}\|^2$', fontsize=28)
    ax_wt.legend(fontsize=20, loc='upper right')
    ax_wt.grid(True, linestyle='--', linewidth=0.5, which='both')
    fig_wt.tight_layout()
    path_wt = os.path.join(save_dir, "term2_hippo_residual_weighted.pdf")
    fig_wt.savefig(path_wt)
    plt.close(fig_wt)
    print(f"Saved: {path_wt}")

    # Print slopes
    for g_item in term2_results["groups"]:
        gid = g_item["group"]
        sl_m = g_item["slope_max"]
        sm = g_item["smoothness_estimate"]
        sl_w = g_item["slope_weighted"]
        if sl_m is not None:
            print(f"Group {gid}: [max] slope={sl_m:.3f}, s≈{sm:.3f}")
        if sl_w is not None:
            print(f"Group {gid}: [weighted] slope={sl_w:.3f}")


# =====================================================================
# Main
# =====================================================================

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--results_path", type=str, required=True)
    p.add_argument("--save_dir", type=str, default="")
    p.add_argument("--x_compress_until", type=int, default=50)
    p.add_argument("--x_left_ratio", type=float, default=1.0 / 3.0)
    args = p.parse_args()

    data = torch.load(args.results_path, map_location="cpu")
    if args.save_dir:
        save_dir = args.save_dir
    else:
        save_dir = os.path.dirname(args.results_path) or "."
    os.makedirs(save_dir, exist_ok=True)

    print(f"Loaded results from: {args.results_path}")
    plot_term1(
        data["term1"],
        save_dir,
        x_compress_until=args.x_compress_until,
        x_left_ratio=args.x_left_ratio,
    )
    plot_term2(data["term2"], save_dir)
    print(f"All figures saved to: {save_dir}")


if __name__ == "__main__":
    main()