agent:
  model:
    name: huggingface/meta-llama/Llama-3.2-1B-Instruct:novita
    api_key: "${HF_TOKEN}"
    per_instance_cost_limit: 0
    total_cost_limit: 0
    per_instance_call_limit: 100
    max_input_tokens: 0
  tools:
    parse_function:
      type: "thought_action"
  history_processors: []